import { PropsWithChildren } from 'react'
import Head from 'next/head'
import Navbar from './Navbar'
import Footer from './Footer'

interface Props {
  title?: string,
  transparent?: boolean
}

export const Layout = (props: PropsWithChildren<Props>) => {


  return (

    <div>
      <Head>
        <title>{props.title}</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" ></link>
      </Head>
      <header>
        <Navbar transparent={true} />
      </header>
      <main>
        {props.children}
      </main>
      <Footer></Footer>
    </div>
  )
}



// import Head from 'next/head'
// import Image from 'next/image'
// import React, { PropsWithChildren } from 'react'
//
// type LayoutProps = {
//   children: React.ReactNode
// }
//
// export const Layout = ({ children }: PropsWithChildren<LayoutProps>) => {
//   return (
//     <div
//       className='flex flex-col flex-1 min-h-screen h-full bg-no-repeat bg-center bg-gradient-to-b from-green-500 to-green-50 bg-cover '
//       style={{
//         backgroundImage: "url('/img/bkn-image.jpg')",
//       }}
//     >
//       <Head>
//         <title>Create Next App</title>
//         <meta name='description' content='Generated by create next app' />
//         <link rel='icon' href='/favicon.ico' />
//       </Head>
//       <header>
//         <section className='flex flex-col justify-center items-center h-1/4 w-full '>
//           <div className='flex flex-col justify-center items-center w-full'>
//             <Image
//               src='/img/Logo.svg'
//               alt='Logo'
//               width={128}
//               height={128}
//               layout='fixed'
//             />
//           </div>
//         </section>
//       </header>
//       <main>{children}</main>
//     </div>
//   )
// }
