import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div
      className='bg-cover bg-no-repeat bg-center'
      style={{
        backgroundImage: "url('/img/bkn-image.jpg')",
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='min-h-screen px-4 flex flex-1 flex-col justify-center items-center'>
        <section className="h-1/4">
          <div className='h-full'>
            <Image src='/img/Logo.svg' alt='Logo' width={298} height={64} layout='responsive' />
          </div>
        </section>

        <div className='h-fit'>
          <span> here it goes the content </span>
        </div>
      </main>

      {/* <footer className={styles.footer}> */}
      {/*   <span> this is the footer </span> */}
      {/* </footer> */}
    </div>
  )
}

export default Home
